let data_dir = '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

call plug#begin()
    Plug 'tpope/vim-sensible'
    Plug 'tpope/vim-fugitive'
    Plug 'tpope/vim-eunuch'
    Plug 'tpope/vim-surround'
    Plug 'tpope/vim-commentary'
    Plug 'noahfrederick/vim-noctu'
    Plug 'itchyny/lightline.vim'
    Plug 'preservim/nerdtree'
    Plug 'mattn/emmet-vim'
    Plug 'w0rp/ale'
    Plug 'airblade/vim-gitgutter'
call plug#end()

map <C-A-o> :NERDTreeToggle<CR>

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent
set number
set colorcolumn=80
set mouse=a
set cursorline
set ttyfast

let g:lightline = {
     \ 'colorscheme': '16color',
    \}
colorscheme noctu
